FROM mysql:5.7

COPY my.cnf /etc/mysql
RUN chmod 0644 /etc/mysql/my.cnf
#RUN mkdir /var/lib/mysql-files
#
#RUN chown -R mysql:mysql /var/lib/mysql-files/
#
#RUN chmod 700 /var/lib/mysql-files/
#
#RUN chown -R mysql:mysql /var/lib/mysql
#RUN chmod 700 /var/lib/mysql